# Generated by Django 5.2.13 on 2026-04-30 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('feed_type', models.CharField(choices=[('STIX/TAXII', 'STIX/TAXII'), ('JSON', 'JSON'), ('CSV', 'CSV'), ('RSS', 'RSS'), ('API', 'API')], default='JSON', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ingested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Feed',
                'verbose_name_plural': 'Threat Feeds',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resolved', 'Resolved'), ('Monitoring', 'Monitoring')], default='Active', max_length=20)),
                ('threat_actor', models.CharField(blank=True, max_length=255, null=True)),
                ('tactics', models.CharField(blank=True, help_text='MITRE ATT&CK tactics', max_length=500, null=True)),
                ('techniques', models.CharField(blank=True, help_text='MITRE ATT&CK techniques', max_length=500, null=True)),
                ('target_sectors', models.CharField(blank=True, help_text='Targeted sectors/industries', max_length=500, null=True)),
                ('target_countries', models.CharField(blank=True, help_text='Target countries', max_length=500, null=True)),
                ('confidence_score', models.FloatField(default=0.5, help_text='AI-generated confidence score')),
                ('correlation_method', models.CharField(blank=True, help_text='Method used for correlation (e.g., DBSCAN)', max_length=100, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Campaign',
                'verbose_name_plural': 'Threat Campaigns',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status'], name='cti_core_th_status_f6d4f7_idx'), models.Index(fields=['-last_seen'], name='cti_core_th_last_se_80bf2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorrelationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicators_count', models.IntegerField()),
                ('correlation_score', models.FloatField()),
                ('method', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlation_logs', to='cti_core.threatcampaign')),
            ],
            options={
                'verbose_name': 'Correlation Log',
                'verbose_name_plural': 'Correlation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_type', models.CharField(choices=[('IPv4', 'IPv4 Address'), ('IPv6', 'IPv6 Address'), ('Domain', 'Domain'), ('URL', 'URL'), ('FileHash-MD5', 'MD5 Hash'), ('FileHash-SHA1', 'SHA1 Hash'), ('FileHash-SHA256', 'SHA256 Hash'), ('Email', 'Email Address'), ('YARA', 'YARA Rule'), ('Malware', 'Malware Family'), ('ASN', 'ASN'), ('CIDR', 'CIDR Block')], max_length=20)),
                ('indicator_value', models.TextField()),
                ('confidence', models.FloatField(default=0.5, help_text='Confidence score between 0 and 1')),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Info', 'Informational')], default='Medium', max_length=20)),
                ('context', models.TextField(blank=True, help_text='Rich contextual information about this indicator', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicators', to='cti_core.threatcampaign')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cti_core.threatfeed')),
            ],
            options={
                'verbose_name': 'Threat Indicator',
                'verbose_name_plural': 'Threat Indicators',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Acknowledged', 'Acknowledged'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved'), ('False Positive', 'False Positive')], default='New', max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='AI-generated explanation of why this alert was triggered', null=True)),
                ('recommended_actions', models.TextField(blank=True, help_text='Recommended response actions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='cti_core.threatcampaign')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cti_core.threatindicator')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['indicator_type', 'indicator_value'], name='cti_core_th_indicat_770035_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['campaign'], name='cti_core_th_campaig_4785b1_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['severity'], name='cti_core_th_severit_bb2d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='threatindicator',
            index=models.Index(fields=['-last_seen'], name='cti_core_th_last_se_62676d_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='cti_core_al_status_e45a32_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='cti_core_al_severit_c31225_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='cti_core_al_created_9b9331_idx'),
        ),
    ]
